FROM node:16.14.0-alpine as builder
RUN mkdir -p /opt/build
WORKDIR /opt/build
COPY ./package.json ./package.json
RUN yarn install

COPY . .
RUN yarn build

FROM node:16.14.0-alpine
RUN mkdir -p /opt/data
COPY --from=builder /opt/build/dist /opt/relayer/dist
WORKDIR /opt/relayer
COPY .env.docker .env
COPY package.json package.json
RUN yarn install --production
COPY ./helix-relayer-runner /usr/local/bin/helix-relayer-runner
CMD [ "helix-relayer-runner"]
